name: Build baselibs

on: [push]

jobs:
  build_baselibs:
    runs-on: ubuntu-latest
    container: gmao/mpi-openmpi:4.0.1 
    steps:
      - name: Install git
        run: |
          yum install -y epel-release
          rpm -U https://centos7.iuscommunity.org/ius-release.rpm
          yum install -y git222
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Checkout submodules
        shell: bash
        run: |
          sed -i 's/git\@github\.com\:/https:\/\/github\.com\//g' .gitmodules
          git submodule init
          git submodule update
      - name: Versions etc.
        run: |
          gfortran --version
          mpirun --version
          echo $BASEDIR
      - name: Install more dependencies
        run: |
          yum install -y byacc bison flex expat-devel texinfo tree
          yum install -y file automake autoconf libtool
          yum install -y epel-release cmake3 && ln -s /usr/bin/cmake3 /usr/bin/cmake
      - name: Build
        run: |
          make -j8 install ESMF_COMM=openmpi CONFIG_SETUP=${config}
      - name: Check
        run: |
          grep -lr "mpirun -n" | xargs sed -i 's/mpirun\ -n/mpirun\ --allow-run-as-root\ -n/g'
          grep -lr "mpiexec -n" | xargs sed -i 's/mpiexec\ -n/mpiexec\ --allow-run-as-root\ -n/g'
          make -j8 check ESMF_COMM=openmpi
      - name: Check directory structure
        run: |
          cd ..
          tree -L 2 x86_64-unknown-linux-gnu/Linux
