name: Build Baselibs
on:
  push:
    branches:
      - main
  release:
    types: 
      - published

jobs:
  build_baselibs:
    runs-on: ubuntu-latest
    container: gmao/ubuntu20-openmpi:4.0.5-gcc_10.2.0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule init
          git submodule update
      - name: Versions etc.
        run: |
          gfortran --version
          mpirun --version
          echo $BASEDIR
      - name: Verify Before
        run: |
          make verify ESMF_COMM=openmpi CC=gcc CXX=g++ FC=gfortran
      - name: Build
        run: |
          make -j4 install ESMF_COMM=openmpi ESMF_PYTHON=/usr/bin/python3 CC=gcc CXX=g++ FC=gfortran
      - name: Verify After
        run: |
          make verify ESMF_COMM=openmpi CC=gcc CXX=g++ FC=gfortran
      - name: Check directory structure
        run: |
          cd ..
          tree -L 2 x86_64-pc-linux-gnu/gfortran/Linux
