name: Build Baselibs
on:
  push:
    branches:
      - main
  release:
    types: 
      - published

jobs:
  build_baselibs:
    runs-on: ubuntu-latest
    container: 
      image: gmao/ubuntu20-openmpi:4.0.5-gcc_10.2.0
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      FC: gfortran
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Versions etc.
        run: |
          gcc --version
          gfortran --version
          mpirun --version
          mpicc --show
          mpic++ --show
          mpifort --show
          echo $BASEDIR
          git submodule status
      - name: Verify Before
        run: |
          make verify ESMF_COMM=openmpi ESMF_COMPILER=gfortran
      - name: Build
        run: |
          make -j4 install ESMF_COMM=openmpi ESMF_PYTHON=/usr/bin/python3 ESMF_COMPILER=gfortran
      - name: Verify After
        run: |
          make verify ESMF_COMM=openmpi ESMF_COMPILER=gfortran
      - name: Check directory structure
        run: |
          cd ..
          tree -L 2 x86_64-pc-linux-gnu/gfortran/Linux
