name: Build Baselibs
on:
  push:
    branches:
      - master
  release:
    types: 
      - published

jobs:
  build_baselibs:
    runs-on: ubuntu-latest
    container: gmao/ubuntu20-openmpi:4.0.5-gcc_10.2.0
    env:
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_TYPE: en_US.UTF-8 
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_btl_vader_single_copy_mechanism: none
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule init
          git submodule update
      - name: Versions etc.
        run: |
          gfortran --version
          mpirun --version
          echo $BASEDIR
      - name: Build
        run: |
          make -j4 install ESMF_COMM=openmpi
      - name: Verify
        run: |
          make verify ESMF_COMM=openmpi
      - name: Check directory structure
        run: |
          cd ..
          tree -L 2 x86_64-pc-linux-gnu/gfortran/Linux
